name = "Rilipack"
author = "septechx"
version = "1.6.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b688e52935a15c055e9e58df5b13177c94f60c43710516419810252931d632fb"

[versions]
forge = "47.4.13"
minecraft = "1.20.1"

[options]
datapack-folder = "datapacks/"
