name = "Rilipack"
author = "septechx"
version = "0.7.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a221358c5d694e559e17690a69f56570ed17abdd80a260a50d4b8a76a2813e8c"

[versions]
forge = "47.4.13"
minecraft = "1.20.1"

[options]
datapack-folder = "datapacks/"
