name = "Rilipack"
author = "septechx"
version = "1.3.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "77b0ed129d95775a39876393a9ba17132bd5e853e5a0d3dfa17083f468c54dd8"

[versions]
forge = "47.4.13"
minecraft = "1.20.1"
