name = "Rilipack"
author = "septechx"
version = "1.3.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "de25bf86d5580f0eb9d542fbf0ce5bf0894afe17975d2b95865e8f42df3593a9"

[versions]
forge = "47.4.13"
minecraft = "1.20.1"
