name = "Rilipack"
author = "septechx"
version = "1.3.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "42f938b2a37bf093b268352669201d2665b00b1642d4a24d9665cf996111cf84"

[versions]
forge = "47.4.13"
minecraft = "1.20.1"
