name = "Rilipack"
author = "septechx"
version = "0.9.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "dc62a92dda22df72c7cbb2db6d2f46df819ed424c8dd8cefe842511d3a8aa1dd"

[versions]
forge = "47.4.13"
minecraft = "1.20.1"

[options]
datapack-folder = "datapacks/"
